### ISSUE TITLE
Monster Tracker Bugged 

### ISSUE THREAD

**Issue by icmayhem** [Excrulon/Tree-of-Savior-Addons#131]
Latest patches everytime I killed a monster, the monster count would appear automatically, however on the newest one it takes 2 seconds for it to appear delaying the results and tracking system,

**Comment by SiKlope** [comment]
In my case, the counter does not appear on the screen when I kill a chupacabra or popolion , I hope that fix soon

**Comment by icmayhem** [comment]
I hope that so too and sad to hear that my friend

**Comment by M081L** [comment]
In my game, the monster tracker seemed to be moved to the side of the monster frame. It confused me a bit in the beggining.

**Comment by Aeolg** [comment]
Currently having the same issue. Started on my alternate Paladin at Sienakal Graveyard. Green Fishermen and Drapel both have achievement counts and both don't show up on the lower right of the screen.

**Comment by DessMendoza** [comment]
Hello  i have kinda the same issue, the addon displays TVE killed red kepas, bit when i got to ashaq underground 3f blues vubbe and mobs from loro jingle dindt got tracked.
