### ISSUE TITLE
BUG: Context Menu addon

### ISSUE THREAD

**Issue by zelasgoto** [Excrulon/Tree-of-Savior-Addons#144]
Right-clicking on the chat text only brings up the normal context menu after the latest version (May 25)

**Comment by zelasgoto** [comment]
Trigger zone for right-click is also strange. It appears to solely trigger about a 1-2 pixels below the message.

**Comment by Miei** [comment]
The trigger zone is to do with IMC's code, not the addon. 

As to why the addon isn't working, I'm going to take a look into it. Strange, though, the patch didn't change anything that should affect this as far as I can see.

**Comment by Excrulon** [comment]
Huh? It wasn't removed. I've been trying to figure out why it isn't working before committing the ipf version.

**Comment by Setmaster** [comment]
Same problem here, no extra options for chat but I still get them when I click on people's chars.
