### ISSUE TITLE
Movement of ExpViewer windows is bugged?

### ISSUE THREAD

**Issue by WinJ9000** [Excrulon/Tree-of-Savior-Addons#147]
The Exp Viewer windows is bugged. 
Everytime i try to move the windows somewhere, it resets back to its original position when i attack/use skills

**Comment by TehSeph** [comment]
>Be sure to press the "R" button at the topright of the experience viewer window in order to save its position after moving it. It will move back if you don't.

**Comment by FlashYoshi** [comment]
@WinJ9000 Did that fix it?

**Comment by WinJ9000** [comment]
Fixed. You need to press the reset button to change the default location of the window

**Comment by WinJ9000** [comment]
Sorry for late reply.. was a bit busy with exams
