### ISSUE TITLE
[Enhancement] Enable/Disable Exp Viewer button

### ISSUE THREAD

**Issue by WinJ9000** [Excrulon/Tree-of-Savior-Addons#148]
Adding a button to turn the Exp Viewer on/off would be nice

**Comment by GustavoBakunin** [comment]
You can disable it on the addonloader.lua on C:/.../TreeofSavior/Addon folder by commenting out the exp viewer line.
![image](https://cloud.githubusercontent.com/assets/17966933/15582490/b2089a8a-2347-11e6-8240-aa9072e957b5.png)

**Comment by laurencee** [comment]
You sort of need a per character setting since there's no reason to show the exp viewer on your 280 characters.

Alternatively you could just not display the exp viewer on level 280 characters by default..

**Comment by BOSS124** [comment]
I made simple modifications on the latest release to add a button that show/hide the expviewer window. It's unofficial and I recommend to make a backup of the original addons files before using these:

[http://puu.sh/p9PHT/9060de3581.zip](url)

**Comment by WinJ9000** [comment]
Thanks a button was also my suggestion of adding since less experienced people kept bugging me on how to temporarily turn it off lol

**Comment by FlashYoshi** [comment]
@BOSS124 Why not make a Pull Request?

**Comment by Excrulon** [comment]
Lot of quality of life changes coming to expviewer today or tomorrow. Will have a way to toggle it as well.

http://i.imgur.com/mPsDn7S.jpg

**Comment by WinJ9000** [comment]
Thanks for the awesome updates!! Keep it up!

**Comment by BOSS124** [comment]
@FlashYoshi Sorry man, it's the first time I use GitHub and I don't know how to use it correctly, I'll learn it with time...

**Comment by FlashYoshi** [comment]
No problem @BOSS124. Next time you can can [fork](https://help.github.com/articles/fork-a-repo/) this repository. There's a button on the main page of the repository.
Then you make your changes in your fork and press the green "[pull request](https://help.github.com/articles/using-pull-requests/)" button on your fork's homepage.

@Excrulon This can be closed I reckon.
