### ISSUE TITLE
Bug: Zoomy doesn't work after a quest boss

### ISSUE THREAD

**Issue by Leftway** [Excrulon/Tree-of-Savior-Addons#150]
After a fight with a quest boss, zoomy doesn't work.
It'll only work after I change channels or change map.
Could you please look into it?
Thanks!

**Comment by metorika** [comment]
yep i experienced the same problem here. would like to suggest an option to perma lock the zoom distance. is it possible to reach the same certain distance every time the key is pressed by changing some config value in zoomy.lua? like "zoom_amount" or "current_zoom" and how do i know what is the current exact value of this "current_zoom" after the key pressed on my screen? thx for your concern. (sry for bad english, im asian and english is not my native language ;/ )

**Comment by ztin** [comment]
same after a camera reset in a quest it doesn't work anymore unless u restart the client XD

**Comment by MarcusReuber** [comment]
Zoomy never really worked for me, I don't know why. maybe it's my keyboard
left alt+ plus or minus doesn't work. How do you use it?

**Comment by Excrulon** [comment]
No longer supporting zoomy.
