### ISSUE TITLE
BetterQuest bug

### ISSUE THREAD

**Issue by galinskas** [Excrulon/Tree-of-Savior-Addons#153]
Every time you level up, the quest log adds some quests as if you had clicked to show them. Then you have to unckeck and check again the "show every quest" box to make the quest log look the way it was before you leveled.

**Comment by Excrulon** [comment]
Doesn't this happen even without betterquest? Thought it did. But yeah it's annoying.

**Comment by S-Loxe** [comment]
Happened to me twice, after the level some random quest are selected even if "Show All Quest"check box is unchecked. Without betterquest I never actually realise, when it first happened I thought I was the one clicking without noticing.

**Comment by galinskas** [comment]
Does it happen without the addon? I think I've been using it for so long that I don't remember...

**Comment by myfirstevercode** [comment]
Is it possible for better quest to auto detect(activate) quest for certain maps below your level you missed (lazy) or at least make the quest on top of the list when you are on a certain maps..

ex.. Tenet (all quest from tenet map would be available first at the top of the list)
then you move to miners village (then all the tenet quest from the top list would be change to miners village quest)

anyway thanks and more power.. nice job there
