### ISSUE TITLE
Pls help, all i want is to contribute

### ISSUE THREAD

**Issue by xpaperjamx** [Excrulon/Tree-of-Savior-Addons#155]
sir, pls guide me, i dont know where to pull or get variable which the game uses, i want to make lua file that i could put into addons folder you've created, something like:

show mob name by default -  coz inside game the only way to see its name is to target lock on it. and also i want to create a lua file which i could recolor mobs name so that i could separate mobs who is a range based mob and a melee mobs. but in order to do it i want to know where i could pull variable of the games, ex: the auto heal pot author where did he get the stat.hp? which the game uses. pls sir enlighten me

**Comment by Excrulon** [comment]
I'd ask @willthedoggy about all of this.

**Comment by xpaperjamx** [comment]
Tnx for the reply, i tried to ask him but as of now he did not answer me sir
