### ISSUE TITLE
Addons Loading Question

### ISSUE THREAD

**Issue by BOSS124** [Excrulon/Tree-of-Savior-Addons#159]
Hello everybody, I'm new here and really want to contribute with this project. I've been looking the addon files and had a question: The addons are automatically loaded from the game? Do the client process load all ipf files from data folder automatically? I need to start making simple addons to see how things works. Thanks

**Comment by xpaperjamx** [comment]
Bro can i ask u a question did u manage to write a script on addons? How to get game variables like if i want to get value of hp? check items or mobs? Or how to pull correct variables which game uses tnx

**Comment by Excrulon** [comment]
yes, game automatically loads ipfs.
