### ISSUE TITLE
Stuck on loadscreen

### ISSUE THREAD

**Issue by kennysan123** [Excrulon/Tree-of-Savior-Addons#162]
Hi bro if my file is on D drive, is this why i cant seem to get it load?

**Comment by Excrulon** [comment]
load button you mean? then delete SumAni.ipf from data folder.

**Comment by kennysan123** [comment]
thanks for replying.  The load ons will just stay on the screen not too
sure why

**Comment by Excrulon** [comment]
I've no idea what you mean...

**Comment by kennysan123** [comment]
ok i will try appreciate that you actially reply man thanks!
