### ISSUE TITLE
How can I reduce the exp viewer's interface size or move position

### ISSUE THREAD

**Issue by phakphumi** [Excrulon/Tree-of-Savior-Addons#165]
I feel like the exp viewer interface is so huge, it's uncomfortable for me when I drag mouse it's always in the exp viewer area. I have tried to move it to another site of my screen but it's always back to original position on screen.
so, how can I fix this problem? or it's no way to do that.

thanks you

**Comment by FlashYoshi** [comment]
See #147 for the jumping back to the original position problem.

**Comment by Excrulon** [comment]
Download latest version of expviewer. Should fix all of this.
