### ISSUE TITLE
Can't uninstall

### ISSUE THREAD

**Issue by yuucreep** [Excrulon/Tree-of-Savior-Addons#166]
So I accidentally deleted an addon manually in ToS folder and now addons manager won't let me reinstall the addon because it is stuck as something that is still installed but won't uninstall. ![ss 2016-06-03 at 06 04 05](https://cloud.githubusercontent.com/assets/19728137/15775650/a06fbf14-29b5-11e6-9f54-39f6abd077e9.png)

Any help?

**Comment by Xanaxiel** [comment]
Download [the ipf file from releases](https://github.com/Excrulon/Tree-of-Savior-Addons/releases/download/brandish/expcardcalculator-v1.0.0.ipf), paste it into your data folder, then rename it to _expcardcalculator-⛄-v1.0.0.ipf. Afterwards uninstall should work.

**Comment by yuucreep** [comment]
It worked! Thanks a lot!

**Comment by Xanaxiel** [comment]
Np!
