### ISSUE TITLE
Button Unistall don't work

### ISSUE THREAD

**Issue by foxusgamer** [Excrulon/Tree-of-Savior-Addons#168]
I Download Tree of savior addon manager , and i install the addons of the program , but when i click Uninstal, dont uninstal , and the button don't desapear. help me please?

**Comment by xdgenesis** [comment]
I deleted all my file in the addon folder and the ipf files of the addons i downloaded, I also deleted the addon.ipf and SumAni.ipf but the tos updater downloads it. I don't know if its related but the uninstall button also doesn't work on me. Please help

**Comment by flamingheart95** [comment]
go delete this %AppData%\tree-of-savior-addon-manager and reinstall the addon

**Comment by Excrulon** [comment]
1d30b23aff007a82886ec6738764fad0b0e6c49d
