### ISSUE TITLE
Moveable Monster Tracker

### ISSUE THREAD

**Issue by TehSeph** [Excrulon/Tree-of-Savior-Addons#17]
Would you mind making the monster tracker window moveable like the exp viewer window is? Having it show up below the quest list and requiring us to move it via editing the lua file (that will be replaced with any future addon updates) is a tad frustrating. :smiley:

**Comment by Excrulon** [comment]
Yeah, been working on something for this. It may be in the next release or two.

**Comment by rncoll7** [comment]
Put
ui.GetFrame("killnotice"):SetOffset(1576, 315);
below
killNoticeFrame:SetGravity(ui.RIGHT, ui.BOTTOM);
in "monstertracker.lua" file for move to under map

**Comment by TehSeph** [comment]
@rncoll7 I did something similar. Moved mine to the left of the map and just below the shouts banner. That only duct-tapes the issue though, not solve it. It seems he's working on it though, so I won't complain and just wait patiently.
