### ISSUE TITLE
[expviewer] incorrect size after teleport

### ISSUE THREAD

**Issue by ShyPixie** [Excrulon/Tree-of-Savior-Addons#170]
I remove some itens from expviewer. After teleport the window changes to an incorrect size:

![bug](http://i.imgur.com/7BNyhxh.png)

**Comment by Excrulon** [comment]
It should resize properly when you gain exp.

**Comment by ShyPixie** [comment]
Why not just call UPDATE_UI before show or something similiar?
You closed it but it remains a bug... and ugly
