### ISSUE TITLE
Experience percentage is not displayed

### ISSUE THREAD

**Issue by lordpegason** [Excrulon/Tree-of-Savior-Addons#171]
When we entered the game the percentage of experience in the addon is not displayed showing the value of 0.00% when in fact this value is originally different.

![bug](https://cloud.githubusercontent.com/assets/19753518/15802340/bd4ed47e-2a84-11e6-9046-316423cfff56.jpg)

Another bug happens when we use the toggle switch / something or when we click on reset session:

![bug02](https://cloud.githubusercontent.com/assets/19753518/15802404/7d18e554-2a87-11e6-823a-f547f3aeeec2.png)

The value of the Current experience and Required is changed to zero.

Post updated @Excrulon

**Comment by Excrulon** [comment]
yeah it calculates when you gain exp.

**Comment by lordpegason** [comment]
Yes. I understand that.

But it would not be interesting to log in to display the initial value equal to the native game experience bar?
