### ISSUE TITLE
expcard - Counting cards that I can't use. 

### ISSUE THREAD

**Issue by wolfeng-db** [Excrulon/Tree-of-Savior-Addons#173]
#At lv75 I got my hands on a lv8 card, so now the addon keeps that value in mind when showing me what level I'll get.

But the problem is I can only use that card once I'm lv120, so is there anyway to prevent the addon from counting certain cards? 

Maybe ignore the ones that are currently locked? 

[example](http://i.imgur.com/RaDBgDc.jpg)

**Comment by Excrulon** [comment]
known issue... put it in storage

**Comment by Excrulon** [comment]
duplicate
