### ISSUE TITLE
No context menu [ToS IDN]

### ISSUE THREAD

**Issue by difara** [Excrulon/Tree-of-Savior-Addons#174]
hello, I'm using this addons and loving it :+1: 
great job on making this tools :)

but I just realized that when I right click on a character, the context menu wont come out, so I can't add friend or inspect or even worse Like them NOOOoooooo
I don't really know if it happens to others or not, since I use this mod in Indonesian ToS server :)

**Comment by difara** [comment]
------------------------------
update : this bug seems to come from context menu addon, after I remove it, everything works normally :)

**Comment by Buksa** [comment]
did you know where 'clear sender messages' ?

**Comment by difara** [comment]
nope :dancer: sorry, I'm new to these mod/helpers things sorry. where is it? can I use this mod if I use that?
