### ISSUE TITLE
[Request?]Mute Sound or...

### ISSUE THREAD

**Issue by rgdoabc** [Excrulon/Tree-of-Savior-Addons#176]
I would love to see a addon to easily mute the game's sounds, something like a button or /mute.

Or a link to where I can learn how to create addons. I already know (a little) about programming, but have no idea how to make a working addon.

**Comment by Navitron** [comment]
https://github.com/Tree-of-Savior-Addon-Community/Addon-Tutorial/wiki
Good resource to get started.

**Comment by Excrulon** [comment]
I'm not doing this as it's in the game's settings already. Feel free to make it yourself!
