### ISSUE TITLE
Cant unninstal Addons

### ISSUE THREAD

**Issue by iluhkz** [Excrulon/Tree-of-Savior-Addons#179]
Ive Unninstaled TOS and then downloaded it again, without uninstaling the mods via Addon Manager.
After the new download of TOS, the addons I was using were listed as installed but they arent in game.
I click to uninstal them but nothing happens. 
Can you help?

**Comment by thailehuy** [comment]
I have same issue. The game suddenly not starts up and I have to reinstall it. Now the addon manager won't uninstall old addons

Please give a guidance on how to clear the addon list

**Comment by allysson-david** [comment]
Delete the folder at %APPDATA%\tree-of-savior-addon-manager and that will reset the Addon Manager.

**Comment by GLCrossheart** [comment]
I also have the issue, but deleting files and folders didn't work at all for me
