### ISSUE TITLE
Show Invested Stat Points no longer working after 08/16/2016 patch.

### ISSUE THREAD

**Issue by DiMeowgio** [Excrulon/Tree-of-Savior-Addons#181]
Show Invested Stat Points no longer appears in the F1 menu.

Verify Game Integrity / Fresh Install of Steam ToS / Re-installation of add-on = Did not work to fix issue.

**Comment by Excrulon** [comment]
Yeah Xanaxiel made a pr to fix it. I'll push it later tonight.

**Comment by DiMeowgio** [comment]
OMG speediest response ever haha! Thanks Excrulon! I'm a big fan of your work :)
