### ISSUE TITLE
where's addon manager's Population?

### ISSUE THREAD

**Issue by excenmille** [Excrulon/Tree-of-Savior-Addons#183]
I had installed Population with the addon manager but can no longer see it in the manager.

**Comment by Excrulon** [comment]
Doesn't work anymore with latest patch and can't be fixed. Removed it.

**Comment by allysson-david** [comment]
May I point that after a specific addon is removed from addons.json it becomes impossible to uninstall it through Addon Manager? Maybe you could add a button to "uninstall removed addons" or something...

**Comment by Excrulon** [comment]
Yeah I know, I'll fix it some day maybe.
