### ISSUE TITLE
how do you compile your lua back to ipf?

### ISSUE THREAD

**Issue by geocine** [Excrulon/Tree-of-Savior-Addons#188]
I modified your betterquest script but I can't seem to make it work when I compiled it back to ipf.  

Steps I did:
1. IPFUnpacker - decrypt
2. IPFSuite - extract
3. Modify Lua
4. IPFSuite - create (add lua and xml files) same structure of original ipf
5. IPFUnpacker - encrypt
6. Replace your ipf with the modified one

Do I have to do anything special to make this work. Because everytime I add my modded IPF it crashes

**Comment by FiftyCaliber** [comment]
It's most likely your code is causing an error which crashes the game.
> 4. IPFSuite - create (add lua and xml files) same structure of original ipf

Just making sure but you made a container called `addon_d.ipf` with `betterquest` folder inside it and your `betterquest.lua` & `betterquest.xml` inside that folder?

**Comment by geocine** [comment]
@FiftyCaliber  yes I did that. same structure . https://dl.dropboxusercontent.com/u/16422464/test/_betterquest-%E2%9B%84-v1.0.0.ipf

**Comment by Excrulon** [comment]
If your change works, pay it forward and make a pull request here so we all can benefit!

**Comment by geocine** [comment]
@Excrulon my change is just for personal use. I mean it would benefit no one. I just displayed the quest class id but I could not make work without it crashing. It worked once but it kept on crashing.
