### ISSUE TITLE
Status window issue after update

### ISSUE THREAD

**Issue by rokuon** [Excrulon/Tree-of-Savior-Addons#189]
Hello sir Excrulon, I'm playing in INA server. I was using ur prev version invested stat which is v1.0.0 which works fine but then I got this error after updating to the v1.0.1. I couldnt see anything in my stat window
![screenshot_20160830_00001](https://cloud.githubusercontent.com/assets/20699194/18064710/d40dffb8-6e5a-11e6-95c4-423a5b20e5f7.jpg)
Will you please help me, I lost track of the stat points I invested

**Comment by Excrulon** [comment]
They're using different code bases so each version is broken on each code base.

Download previous version here and replace v1.0.1 with this one. Make sure to put a ⛄ in the filename...

https://github.com/Excrulon/Tree-of-Savior-Addons/releases/download/brandish/showinvestedstatpoints-v1.0.0.ipf

**Comment by rokuon** [comment]
Thank you sir, omg ure online, tried to look for you in steam but ure offline thank you again for the fast reply, will report how its going!

**Comment by rokuon** [comment]
It works!! thank you so much TT please accept my friend request in steam sir :D ure the best!
![screenshot_20160830_00002](https://cloud.githubusercontent.com/assets/20699194/18067284/5170b080-6e66-11e6-9890-c970117b4b93.jpg)
