### ISSUE TITLE
Ping

### ISSUE THREAD

**Issue by xator91** [Excrulon/Tree-of-Savior-Addons#29]
Can you add ping ms in the addon?

**Comment by TehSeph** [comment]
https://treeofsavior.com/news/?n=372 might be of use to you.

**Comment by xator91** [comment]
I mean, check realtime ping on server, just for see if you're lagging or not

**Comment by pedrosotero** [comment]
just use the //ping comand on /s chat

**Comment by xator91** [comment]
//ping show me 0.19238 i dont think it's my real ping

**Comment by Excrulon** [comment]
it is, that's a ping of 192 ms.

**Comment by xator91** [comment]
It's not possible. Because if i ping with command prompt i have 42ms. And however is better to have realtime ping under FPS

**Comment by Excrulon** [comment]
The ip you're pinging is probably just the login server. Completely different when in game.
